### ISSUE TITLE
Can not import models in Blender 4.1

### ISSUE THREAD

**Issue by Maxandkon** [Greatness7/io_scene_mw#13]
Greeting.
On the latest version of Blender (4.1), I get this same error with all .nif Morrowind files
```
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1232, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_mw\nif_import.py", line 12, in <module>
    from es3.utils import meshoptimizer
ImportError: cannot import name 'meshoptimizer' from 'es3.utils' (unknown location)
```

**Comment by JobediahTimberman** [comment]
Blender 4.1 uses Python 3.11, and it appears meshoptimizer is compiled for 3.10. Hopefully all that's needed is a new meshoptimizer compile.
