### ISSUE TITLE
Unable to import NIF file

### ISSUE THREAD

**Issue by rcrandall72** [Greatness7/io_scene_mw#16]
Have tried Blender 3.1, 3.3 and 4.2, installed Redistributable, and added package to Blender

Python: Traceback (most recent call last):
  File "C:\Users\ryand\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_mw\__init__.py", line 387, in execute
    return nif_import.load(context, **kwargs)
  File "C:\Users\ryand\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_mw\nif_import.py", line 34, in load
    importer.execute()
  File "C:\Users\ryand\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_mw\nif_import.py", line 63, in execute
    data.load(self.filepath)
  File "C:\Users\ryand\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_mw\lib\es3\nif\NiStream.py", line 22, in load
    assert stream.readline() == self.HEADER
AssertionError

location: <unknown location>:-1

**Comment by Greatness7** [comment]
Can you attach the file here? Judging from the error message it's either a corrupte file, or a non-Morrowind NIF version.

**Comment by ianspilios** [comment]
The exact same thing is happening to me

**Comment by Calandiel** [comment]
Same here, the error message is the same as @ianspilios 's

**Comment by Greatness7** [comment]
The plugin does not currently work with Blender 4.2. For now you'll have to downgrade to 4.1.

**Comment by Calandiel** [comment]
I managed to make a hacky fix it for my local machine for 4.2.

Here's the project, in case someone else stumbles upon the same issue and needs an easier starting point:
[io_scene_mw.zip](https://github.com/user-attachments/files/17347718/io_scene_mw.zip)

You'd need to modify the path to textures in `nif_import.py` to point to your directory (search for `/home/desu/` and then modify the string).
