### ISSUE TITLE
StopIteration exception on importing Falconer Leather

### ISSUE THREAD

**Issue by BPaden** [Greatness7/io_scene_mw#2]
Want to try my hand at making adjustments to make these clothes fit roberts bodies. When I try to import KO_FalconerFem_LacePants.nif from [this mod](http://mw.modhistory.com/download-44-12242), I get the following exception.

```
Traceback (most recent call last):
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/__init__.py", line 380, in execute
    return nif_import.load(context, **kwargs)
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 35, in load
    importer.load(filepath)
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 77, in load
    self.resolve_armatures()
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 116, in resolve_armatures
    root = next(n.source for n in self.nodes if self.armatures.get(n.source))
StopIteration

location: <unknown location>:-1
```

This is on Arch Linux with Blender 2.83, python 3.8.3 and io_scene_mw 0.8.22.

**Comment by Greatness7** [comment]
This file has some funky things going on inside it. It has "Bip01" specified as its root node, but the scene graph within actually defines another root node, named "Scene Root". Properly handling this inconsistency may take awhile to iron out, but in the meantime simply re-saving the file in Nifskope should fix the error.
