### ISSUE TITLE
Roberts bodies AttributeError

### ISSUE THREAD

**Issue by BPaden** [Greatness7/io_scene_mw#3]
when loading Meshes/_GL_B/Br/m.nif from robert's bodies I get the following error. Actually, for accuracy, I think the exact mesh comes from [this](https://www.nexusmods.com/morrowind/mods/43685) compatibility mod from Galib.

```
Traceback (most recent call last):
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/__init__.py", line 380, in execute
    return nif_import.load(context, **kwargs)
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 35, in load
    importer.load(filepath)
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 73, in load
    roots = self.resolve_nodes(data.roots)
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 95, in resolve_nodes
    root_nodes = [SceneNode(self, root, parent) for root in ni_roots]
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 95, in <listcomp>
    root_nodes = [SceneNode(self, root, parent) for root in ni_roots]
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/nif_import.py", line 289, in __init__
    self.matrix_local = np.asarray(source.matrix, dtype="<f")
  File "/home/aaron/.config/blender/2.83/scripts/addons/io_scene_mw/lib/es3/nif/NiObject.py", line 23, in __getattr__
    raise AttributeError(f"'{self.type}' has no attribute '{name}'")
AttributeError: 'NiSkinInstance' has no attribute 'matrix'

location: <unknown location>:-1
```

This is on Arch Linux with Blender 2.83, python 3.8.3 and io_scene_mw 0.8.22.

**Comment by Greatness7** [comment]
I am unable to reproduce the error with the `m.nif` from that mod. Are you sure your copy has not been modified? If you're able to share a link to it here that would help.

**Comment by BPaden** [comment]
Not positive. I'll try to confirm the exact model.
